SECRET_KEY = "SECRET_KEY"
EMAIL_HOST = 'EMAIL_HOST'
SERVER_EMAIL = DEFAULT_FROM_EMAIL = EMAIL_HOST_USER = 'SERVER_EMAIL'
EMAIL_HOST_PASSWORD = 'EMAIL_HOST_PASSWORD'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
MANAGERS = ADMINS = (
    #('You', 'you@email.com'),
)
#DATABASES
